In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
sold_dfs = []

for year in [2024, 2026]:
    for month in range(1, 13):
        fname = f"CRMLSSold{year}{month:02d}.csv"
        try:
            df = pd.read_csv(fname)
            df['Year'] = year
            df['Month'] = month
            sold_dfs .append(df)
        except FileNotFoundError:
            # Skip months that don't exist yet
            continue

# If you want one big DataFrame:
all_sold_df = pd.concat(sold_dfs, ignore_index=True)

/var/folders/b9/2nft45yn149gpklybfl7lll40000gp/T/ipykernel_1999/3541173211.py:7: DtypeWarning: Columns (2,36,39,56,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(fname)
/var/folders/b9/2nft45yn149gpklybfl7lll40000gp/T/ipykernel_1999/3541173211.py:7: DtypeWarning: Columns (4,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(fname)

In [4]:
all_sold_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308054 entries, 0 to 308053
Data columns (total 86 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   BuyerAgentAOR                 238610 non-null  object
 1   ListAgentAOR                  240124 non-null  object
 2   Flooring                      181076 non-null  object
 3   ViewYN                        277231 non-null  object
 4   WaterfrontYN                  167 non-null     object
 5   BasementYN                    5077 non-null    object
 6   PoolPrivateYN                 265426 non-null  object
 7   OriginalListPrice             307198 non-null  float64
 8   ListingKey                    308054 non-null  int64
 9   ListAgentEmail                288535 non-null  object
 10  CloseDate                     308054 non-null  object
 11  ClosePrice                    308050 non-null  float64
 12  ListAgentFirstName            306025 non-null  object
 13  ListAgentLastName             308027 non-null  object
 14  Latitude                      289327 non-null  float64
 15  Longitude                     289478 non-null  float64
 16  UnparsedAddress               307576 non-null  object
 17  PropertyType                  308054 non-null  object
 18  LivingArea                    286198 non-null  float64
 19  ListPrice                     307610 non-null  float64
 20  DaysOnMarket                  308054 non-null  int64
 21  ListOfficeName                308054 non-null  object
 22  BuyerOfficeName               303432 non-null  object
 23  CoListOfficeName              62688 non-null   object
 24  ListAgentFullName             307987 non-null  object
 25  CoListAgentFirstName          62392 non-null   object
 26  CoListAgentLastName           62526 non-null   object
 27  BuyerAgentMlsId               307290 non-null  object
 28  BuyerAgentFirstName           306493 non-null  object
 29  BuyerAgentLastName            307890 non-null  object
 30  FireplacesTotal               0 non-null       float64
 31  AssociationFeeFrequency       91513 non-null   object
 32  AboveGradeFinishedArea        0 non-null       float64
 33  ListingKeyNumeric             308054 non-null  int64
 34  MLSAreaMajor                  274305 non-null  object
 35  TaxAnnualAmount               1517 non-null    float64
 36  CountyOrParish                308054 non-null  object
 37  MlsStatus                     308054 non-null  object
 38  ElementarySchool              35600 non-null   object
 39  AttachedGarageYN              224374 non-null  object
 40  ParkingTotal                  297748 non-null  float64
 41  BuilderName                   11795 non-null   object
 42  PropertySubType               283810 non-null  object
 43  LotSizeAcres                  276489 non-null  float64
 44  SubdivisionName               107624 non-null  object
 45  BuyerOfficeAOR                296215 non-null  object
 46  YearBuilt                     295063 non-null  float64
 47  StreetNumberNumeric           307244 non-null  float64
 48  ListingId                     308054 non-null  object
 49  BathroomsTotalInteger         293519 non-null  float64
 50  City                          307745 non-null  object
 51  TaxYear                       190 non-null     float64
 52  BuildingAreaTotal             38781 non-null   float64
 53  BedroomsTotal                 287266 non-null  float64
 54  ContractStatusChangeDate      307342 non-null  object
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         24709 non-null   object
 57  PurchaseContractDate          301861 non-null  object
 58  ListingContractDate           308009 non-null  object
 59  BelowGradeFinishedArea        1234 non-null    float64
 60  BusinessType                  911 non-null     object
 61  StateOrProvince               308054 non-null  object
 62  CoveredSpaces                 0 non-null       float64
 63  MiddleOrJuniorSchool          35850 non-null   object
 64  FireplaceYN                   280569 non-null  object
 65  Stories                       241552 non-null  float64
 66  HighSchool                    46421 non-null   object
 67  Levels                        260577 non-null  object
 68  LotSizeDimensions             15659 non-null   object
 69  LotSizeArea                   277514 non-null  float64
 70  MainLevelBedrooms             160699 non-null  float64
 71  NewConstructionYN             271609 non-null  object
 72  GarageSpaces                  269358 non-null  float64
 73  HighSchoolDistrict            207265 non-null  object
 74  PostalCode                    307959 non-null  object
 75  AssociationFee                211614 non-null  float64
 76  LotSizeSquareFeet             277271 non-null  float64
 77  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 78  OriginatingSystemName         37052 non-null   object
 79  OriginatingSystemSubName      37052 non-null   object
 80  Year                          308054 non-null  int64
 81  Month                         308054 non-null  int64
 82  BuyerAgencyCompensationType   67747 non-null   object
 83  BuyerAgencyCompensation       67780 non-null   float64
 84  latfilled                     77055 non-null   object
 85  lonfilled                     77055 non-null   object
dtypes: float64(28), int64(5), object(53)
memory usage: 202.1+ MB

In [3]:
print("Preview of Concatenated Sold DataFrame")
display(all_sold_df.head())

print("---------/--------")
print("All columns in DataFrame\n")
print(all_sold_df.columns)
print("---------/--------")
print("Description of DataFrame\n")
print(all_sold_df.describe)

Preview of Concatenated Sold DataFrame

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName,Year,Month,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,...,NaN,NaN,CRMLS,CRMLS_MLSL,2024,1,NaN,NaN,NaN,NaN
1,HighDesert,HighDesert,NaN,NaN,NaN,NaN,NaN,0.0,535486633,eabrown@lee-associates.com,...,52320.0,NaN,CRMLS,CRMLS_CRM,2024,1,NaN,NaN,NaN,NaN
2,OrangeCounty,OrangeCounty,NaN,True,NaN,NaN,NaN,75000.0,529986282,Joe@9WINWIN.com,...,217364.0,NaN,CRMLS,CRMLS_CRM,2024,1,NaN,NaN,NaN,NaN
3,InlandValleys,InlandValleys,NaN,True,NaN,NaN,NaN,199000.0,529618166,carolthefinder@yahoo.com,...,217800.0,NaN,CRMLS,CRMLS_CRM,2024,1,NaN,NaN,NaN,NaN
4,SouthwestRiversideCounty,SouthwestRiversideCounty,NaN,True,NaN,NaN,NaN,19500.0,522614340,jtavisola@tavisola.com,...,108883.0,NaN,CRMLS,CRMLS_CRM,2024,1,NaN,NaN,NaN,NaN

---------/--------
All columns in DataFrame

Index(['BuyerAgentAOR', 'ListAgentAOR', 'Flooring', 'ViewYN', 'WaterfrontYN',
       'BasementYN', 'PoolPrivateYN', 'OriginalListPrice', 'ListingKey',
       'ListAgentEmail', 'CloseDate', 'ClosePrice', 'ListAgentFirstName',
       'ListAgentLastName', 'Latitude', 'Longitude', 'UnparsedAddress',
       'PropertyType', 'LivingArea', 'ListPrice', 'DaysOnMarket',
       'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName',
       'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName',
       'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName',
       'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'MlsStatus', 'ElementarySchool', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'StreetNumberNumeric',
       'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'StateOrProvince', 'CoveredSpaces',
       'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool',
       'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict',
       'OriginatingSystemName', 'OriginatingSystemSubName', 'Year', 'Month',
       'BuyerAgencyCompensationType', 'BuyerAgencyCompensation', 'latfilled',
       'lonfilled'],
      dtype='object')
---------/--------
Description of DataFrame

<bound method NDFrame.describe of                    BuyerAgentAOR              ListAgentAOR          Flooring  \
0                    Mlslistings               Mlslistings  Carpet,Tile,Wood
1                     HighDesert                HighDesert               NaN
2                   OrangeCounty              OrangeCounty               NaN
3                  InlandValleys             InlandValleys               NaN
4       SouthwestRiversideCounty  SouthwestRiversideCounty               NaN
...                          ...                       ...               ...
308049          CaliforniaDesert          CaliforniaDesert       Carpet,Tile
308050         JoshuaTreeGateway         JoshuaTreeGateway               NaN
308051                 Southland                 Southland               NaN
308052             InlandValleys             InlandValleys               NaN
308053              OrangeCounty               TriCounties               NaN

       ViewYN WaterfrontYN BasementYN PoolPrivateYN  OriginalListPrice  \
0        True          NaN        NaN         False           499000.0
1         NaN          NaN        NaN           NaN                0.0
2        True          NaN        NaN           NaN            75000.0
3        True          NaN        NaN           NaN           199000.0
4        True          NaN        NaN           NaN            19500.0
...       ...          ...        ...           ...                ...
308049   True          NaN        NaN          True            11500.0
308050   True          NaN        NaN           NaN           250000.0
308051   True          NaN        NaN           NaN            49999.0
308052   True          NaN        NaN           NaN           299900.0
308053  False          NaN        NaN           NaN           900000.0

        ListingKey              ListAgentEmail  ... LotSizeSquareFeet  \
0        551985747       jwachter@cbnorcal.com  ...               NaN
1        535486633  eabrown@lee-associates.com  ...           52320.0
2        529986282             Joe@9WINWIN.com  ...          217364.0
3        529618166    carolthefinder@yahoo.com  ...          217800.0
4        522614340      jtavisola@tavisola.com  ...          108883.0
...            ...                         ...  ...               ...
308049  1020380240                         NaN  ...           13504.0
308050  1019908389                         NaN  ...          328878.0
308051   541645473                         NaN  ...          104024.0
308052   532189426                         NaN  ...           60113.0
308053   425835813                         NaN  ...           82800.0

        MiddleOrJuniorSchoolDistrict OriginatingSystemName  \
0                                NaN                 CRMLS
1                                NaN                 CRMLS
2                                NaN                 CRMLS
3                                NaN                 CRMLS
4                                NaN                 CRMLS
...                              ...                   ...
308049                           NaN                 CRMLS
308050                           NaN                 CRMLS
308051                           NaN                 CRMLS
308052                           NaN                 CRMLS
308053                           NaN                 CRMLS

       OriginatingSystemSubName  Year  Month BuyerAgencyCompensationType  \
0                    CRMLS_MLSL  2024      1                         NaN
1                     CRMLS_CRM  2024      1                         NaN
2                     CRMLS_CRM  2024      1                         NaN
3                     CRMLS_CRM  2024      1                         NaN
4                     CRMLS_CRM  2024      1                         NaN
...                         ...   ...    ...                         ...
308049               CRMLS_CDAR  2026      2                         NaN
308050                CRMLS_CRM  2026      2                         NaN
308051                CRMLS_CRM  2026      2                         NaN
308052                CRMLS_CRM  2026      2                         NaN
308053                CRMLS_CRM  2026      2                         NaN

       BuyerAgencyCompensation  latfilled  lonfilled
0                          NaN        NaN        NaN
1                          NaN        NaN        NaN
2                          NaN        NaN        NaN
3                          NaN        NaN        NaN
4                          NaN        NaN        NaN
...                        ...        ...        ...
308049                     NaN        NaN        NaN
308050                     NaN        NaN        NaN
308051                     NaN        NaN        NaN
308052                     NaN        NaN        NaN
308053                     NaN        NaN        NaN

[308054 rows x 86 columns]>

In [7]:
prop_type = all_sold_df['PropertyType'].unique()
print(prop_type)

['Residential' 'CommercialLease' 'Land' 'ResidentialLease'
 'ManufacturedInPark' 'ResidentialIncome' 'CommercialSale'
 'BusinessOpportunity']

In [10]:
residential_sold_df=all_sold_df[all_sold_df['PropertyType']=='Residential']
residential_sold_df.info()
display(residential_sold_df.head())

<class 'pandas.core.frame.DataFrame'>
Index: 208629 entries, 0 to 308044
Data columns (total 86 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   BuyerAgentAOR                 161208 non-null  object
 1   ListAgentAOR                  162468 non-null  object
 2   Flooring                      133690 non-null  object
 3   ViewYN                        191045 non-null  object
 4   WaterfrontYN                  127 non-null     object
 5   BasementYN                    4061 non-null    object
 6   PoolPrivateYN                 187555 non-null  object
 7   OriginalListPrice             208267 non-null  float64
 8   ListingKey                    208629 non-null  int64
 9   ListAgentEmail                196025 non-null  object
 10  CloseDate                     208629 non-null  object
 11  ClosePrice                    208627 non-null  float64
 12  ListAgentFirstName            206866 non-null  object
 13  ListAgentLastName             208615 non-null  object
 14  Latitude                      192942 non-null  float64
 15  Longitude                     192942 non-null  float64
 16  UnparsedAddress               208442 non-null  object
 17  PropertyType                  208629 non-null  object
 18  LivingArea                    208507 non-null  float64
 19  ListPrice                     208629 non-null  float64
 20  DaysOnMarket                  208629 non-null  int64
 21  ListOfficeName                208629 non-null  object
 22  BuyerOfficeName               204471 non-null  object
 23  CoListOfficeName              46974 non-null   object
 24  ListAgentFullName             208593 non-null  object
 25  CoListAgentFirstName          46732 non-null   object
 26  CoListAgentLastName           46858 non-null   object
 27  BuyerAgentMlsId               208391 non-null  object
 28  BuyerAgentFirstName           207460 non-null  object
 29  BuyerAgentLastName            208541 non-null  object
 30  FireplacesTotal               0 non-null       float64
 31  AssociationFeeFrequency       86727 non-null   object
 32  AboveGradeFinishedArea        0 non-null       float64
 33  ListingKeyNumeric             208629 non-null  int64
 34  MLSAreaMajor                  181183 non-null  object
 35  TaxAnnualAmount               0 non-null       float64
 36  CountyOrParish                208629 non-null  object
 37  MlsStatus                     208629 non-null  object
 38  ElementarySchool              28821 non-null   object
 39  AttachedGarageYN              177556 non-null  object
 40  ParkingTotal                  208204 non-null  float64
 41  BuilderName                   10182 non-null   object
 42  PropertySubType               208259 non-null  object
 43  LotSizeAcres                  190720 non-null  float64
 44  SubdivisionName               76276 non-null   object
 45  BuyerOfficeAOR                198487 non-null  object
 46  YearBuilt                     208442 non-null  float64
 47  StreetNumberNumeric           208403 non-null  float64
 48  ListingId                     208629 non-null  object
 49  BathroomsTotalInteger         208587 non-null  float64
 50  City                          208405 non-null  object
 51  TaxYear                       0 non-null       float64
 52  BuildingAreaTotal             14026 non-null   float64
 53  BedroomsTotal                 208621 non-null  float64
 54  ContractStatusChangeDate      208040 non-null  object
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         18625 non-null   object
 57  PurchaseContractDate          208448 non-null  object
 58  ListingContractDate           208628 non-null  object
 59  BelowGradeFinishedArea        1072 non-null    float64
 60  BusinessType                  0 non-null       object
 61  StateOrProvince               208629 non-null  object
 62  CoveredSpaces                 0 non-null       float64
 63  MiddleOrJuniorSchool          29012 non-null   object
 64  FireplaceYN                   208480 non-null  object
 65  Stories                       172645 non-null  float64
 66  HighSchool                    37405 non-null   object
 67  Levels                        184532 non-null  object
 68  LotSizeDimensions             9855 non-null    object
 69  LotSizeArea                   190992 non-null  float64
 70  MainLevelBedrooms             118967 non-null  float64
 71  NewConstructionYN             193683 non-null  object
 72  GarageSpaces                  200104 non-null  float64
 73  HighSchoolDistrict            152951 non-null  object
 74  PostalCode                    208629 non-null  object
 75  AssociationFee                159580 non-null  float64
 76  LotSizeSquareFeet             190937 non-null  float64
 77  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 78  OriginatingSystemName         23497 non-null   object
 79  OriginatingSystemSubName      23497 non-null   object
 80  Year                          208629 non-null  int64
 81  Month                         208629 non-null  int64
 82  BuyerAgencyCompensationType   46136 non-null   object
 83  BuyerAgencyCompensation       46125 non-null   float64
 84  latfilled                     52908 non-null   object
 85  lonfilled                     52908 non-null   object
dtypes: float64(28), int64(5), object(53)
memory usage: 138.5+ MB

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName,Year,Month,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,...,NaN,NaN,CRMLS,CRMLS_MLSL,2024,1,NaN,NaN,NaN,NaN
5,SanDiego,SanDiego,NaN,False,NaN,NaN,False,759900.0,522107581,mdarwich12@gmail.com,...,NaN,NaN,CRMLS,CRMLS_SAND,2024,1,NaN,NaN,NaN,NaN
9,SanDiego,SanDiego,NaN,False,NaN,NaN,False,739900.0,510919001,mdarwich12@gmail.com,...,NaN,NaN,CRMLS,CRMLS_SAND,2024,1,NaN,NaN,NaN,NaN
28,Mlslistings,Mlslistings,NaN,False,NaN,NaN,NaN,NaN,1079166779,davidmartz@compass.com,...,13504.0,NaN,CRMLS,CRMLS_MLSL,2024,1,NaN,NaN,NaN,NaN
29,Southland,Southland,NaN,False,NaN,NaN,False,1890500.0,1075037759,karen.klein@theagencyre.com,...,17873.0,NaN,CRMLS,CRMLS_CRM,2024,1,NaN,NaN,NaN,NaN

In [ ]:
completedness = residential_sold_df.isnull().sum()

BuyerAgentAOR                   47421
ListAgentAOR                    46161
Flooring                        74939
ViewYN                          17584
WaterfrontYN                   208502
                                ...
Month                               0
BuyerAgencyCompensationType    162493
BuyerAgencyCompensation        162504
latfilled                      155721
lonfilled                      155721
Length: 86, dtype: int64